services:
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3000:3000
    stdin_open: true
    restart: always
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: backend
      target: development
    depends_on:
      - mongo
    expose: 
      - 3000
  mongo:
    restart: always
    image: mongo:4.2.0
    expose:
      - 27017
